### ISSUE TITLE
Storage Usage indicator problem

### ISSUE THREAD

**Issue by Clements-Peter** [kyantech/Palmr#110]
Hi,
On my Synology NAS DS918+ I installed Palmr with the portainer, however from version 3b9 on (so also with the latest version), I get the following indication

![Image](https://github.com/user-attachments/assets/b0b3c00d-8bc5-4614-a580-b3aa8fa12e0a)

versions before (like b7 or b8), I had this indication => note that the available storage is also 0B

![Image](https://github.com/user-attachments/assets/92fbb713-529a-40ec-88e8-078954c4e0c7)

I checked the rights on the palmr folder and it's subfolders to R/W rights to "everyone".

Any idea what I could try else ?
Thanks!

**Comment by danielalves96** [comment]
Hey @Clements-Peter !

This error indicates that Palmr. cannot determine disk space using any available system methods. This is **primarily a permissions or system configuration issue**.

## What's Happening

The system tries multiple approaches to get disk space information:
1. **Linux/macOS**: Uses `df` commands (`df -B1`, `df -k`, `df`)  
2. **Windows**: Uses `wmic logicaldisk` command
3. **Paths tested**: `/app/server/uploads`, `/app/server`, `/app`, `/` (in containers)

When **all methods fail**, you get this critical error.

## Troubleshooting Steps

### 1. Check Container Access (Most Important)

```bash
# Enter your container
docker exec -it <your_palmr_container_name> bash

# Test basic disk utilities
df -h
df -k /app/server/uploads

# Check if paths exist and permissions
ls -la /app/server/
ls -la /app/server/uploads/
ls -la /app/

# Check what user the process runs as
whoami
id
```

### 2. Common Solutions

**If `df` command doesn't work:**
```bash
# Your container might be too minimal - install disk utilities
apt-get update && apt-get install -y coreutils
# or
apk add coreutils  # for Alpine-based images
```

**If permission errors:**
```bash
# Fix directory permissions
chown -R 1000:1000 /app/server/uploads/
chmod -R 755 /app/server/uploads/

# Or create missing directories
mkdir -p /app/server/uploads
chmod 755 /app/server/uploads
```

### 3. Docker Configuration Check

Verify your `docker-compose.yml`:
```yaml
services:
  palmr:
    volumes:
      - ./uploads:/app/server/uploads
      - ./temp-chunks:/app/server/temp-chunks
    # Remove or adjust user restrictions if too restrictive
    # user: "1000:1000"  # Comment this out temporarily
```

### 4. Manual Verification

**Outside container:**
```bash
# Check if host directories exist and have correct permissions
ls -la ./uploads/
ls -la ./temp-chunks/

# Fix host permissions if needed
sudo chown -R $USER:$USER ./uploads/
sudo chmod -R 755 ./uploads/
```

### 5. Alternative Workarounds

**Option A: Use non-admin user temporarily**
- Access Palmr as a regular user instead of admin
- The system will use user quotas instead of actual disk space

**Option B: Mount with proper permissions**
```yaml
volumes:
  - ./uploads:/app/server/uploads:rw
  - ./temp-chunks:/app/server/temp-chunks:rw
```

**Option C: Run container with elevated permissions temporarily**
```yaml
privileged: true  # Add this temporarily for testing
```

## Quick Diagnosis

Run this **one-liner** to diagnose:
```bash
docker exec -it <container_name> sh -c "whoami && df -h && ls -la /app/server/ && echo 'Test complete'"
```

**Expected output should show:**
- Username (not root ideally, but should have access)
- Disk usage information  
- Directory listings without permission errors

## Most Likely Solutions

1. **90% of cases**: Directory permission issue → Fix with `chown`/`chmod`
2. **5% of cases**: Missing `df` utility → Install `coreutils` 
3. **5% of cases**: Docker volume mounting issue → Fix `docker-compose.yml`

Let me know what the diagnostic command returns and I can provide more specific guidance!

**Comment by shpress** [comment]
@danielalves96 I am having a similar issue: 

docker exec -it palmr sh -c "whoami && df -h && ls -la /app/server/ && echo 'Test complete'"
root
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     9.7G         0      9.7G   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /app/server
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /etc/resolv.conf
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /etc/hostname
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /etc/hosts
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /app/server/uploads
/dev/mapper/cachedev_0
                        447.4G     89.5G    357.9G  20% /app/server/temp-chunks
total 0
drwxr-xr-x    1 root     root            72 Jul  8 01:54 .
drwxr-xr-x    1 palmr    nodejs          82 Jul  7 19:48 ..
drwxr-xr-x    1 palmr    nodejs          30 Jul  8 01:54 prisma
drwxr-xr-x    1 node     node             0 Jul  8 01:49 temp-chunks
drwxr-xr-x    1 root     root             0 Jul  8 01:54 temp-uploads
drwxr-xr-x    1 node     node             0 Jul  8 01:49 uploads
Test complete

Any guidance? 

services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    privileged: true  
    environment:
       ENABLE_S3: false
       ENCRYPTION_KEY: 
      - 5487:5487
      - 3333:3333
    volumes:
      - /volume3/docker/palmr/uploads:/app/server/uploads
      - /volume3/docker/palmr/temp-chunks:/app/server/temp-chunks
    restart: on-failure:5

**Comment by danielalves96** [comment]
Hey @shpress !

I'm still investigating the root cause, I had forgotten to tag the issue earlier. I haven't pinpointed the exact source of the problem yet. As soon as I have more details or a version with the fix, I'll share an update here in this thread.

**Comment by danielalves96** [comment]
@Clements-Peter @shpress 

I've been researching the issue for the past few days. I've noticed from a series of issues here on GitHub that the problem is specific to Synology NAS, but it can also occur in other environments. Because of this, I've applied some code fixes and added some specific cases for Synology NAS to correctly capture disk space.

However, I don't have access to a Synology environment to perform the tests, so I'm asking for your help with this testing and validation if possible. Below, I'll include some dockerfile options for testing, using a specific docker image I generated for testing. The version is `v3.1.1-rc.1`

## Synology NAS Test

### Step 1: Create Directory Structure
```bash
# SSH into your Synology NAS or use Terminal in DSM
sudo mkdir -p /volume1/docker/palmr/{uploads,temp-uploads,temp-chunks,prisma}

# Set proper permissions for Synology NAS
sudo chown -R 1000:1000 /volume1/docker/palmr/
sudo chmod -R 755 /volume1/docker/palmr/

# Verify the permissions
ls -la /volume1/docker/palmr/
```

### Step 2: Create Docker Compose File

```yaml
version: '3.8'

services:
  palmr:
    image: kyantech/palmr:v3.1.1-rc.1
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=palmr-test-encryption-key-2025
      - PALMR_UID=1000 # UID for Synology NAS compatibility (default is 1001)
      - PALMR_GID=1000 # GID for Synology NAS compatibility (default is 1001)
    ports:
      - "5487:5487"
      - "3333:3333"
    volumes:
      - /volume1/docker/palmr/uploads:/app/server/uploads
      - /volume1/docker/palmr/temp-uploads:/app/server/temp-uploads
      - /volume1/docker/palmr/temp-chunks:/app/server/temp-chunks
      - /volume1/docker/palmr/prisma:/app/server/prisma
    restart: unless-stopped
EOF
```

### Step 3: Start the Container

### Step 4: Test the Web Interface

If you are unsure about your permission you can do the following:

####  Find Your UID/GID
```bash
# Check your current user
id
# Output example: uid=1026(sc-download) gid=100(users) groups=100(users),101(administrators)

# Or check who owns the volume directories
ls -la /volume1/docker/
ls -la /volume1/docker/palmr/
```

If necessary, you can change the environment variables `PALMR_UID` and `PALMR_GID` with the necessary values and then change the directory permissions:

Set permissions to match your custom UID/GID (**Just example values here as 1026 and 100**)

```bash
sudo chown -R 1026:100 /volume1/docker/palmr/
sudo chmod -R 755 /volume1/docker/palmr/
```

### Common UID/GID Values

| System | Typical UID | Typical GID | Notes |
|--------|-------------|-------------|-------|
| Synology NAS | 1000 | 1000 | Most common |
| Synology Docker | 1026 | 100 | sc-download user |
| Standard Linux | 1000 | 1000 | Default user |
| Custom Setup | Varies | Varies | Check with `id` command |


## 🔍 Troubleshooting Commands

### Check Container Status
```bash
docker ps | grep palmr
```

### Verify Volume Mounts and Permissions
```bash
docker exec -it palmr ls -la /app/server/
docker exec -it palmr whoami
docker exec -it palmr id
```

### Test Disk Space Detection
```bash
docker exec -it palmr df -h /app/server/uploads
docker exec -it palmr df -h /app/server/temp-uploads
```

### Check Mount Points
```bash
docker exec -it palmr cat /proc/mounts | grep volume
```

### Verify UID/GID Configuration
```bash
# Check if container is running with correct user
docker exec -it palmr sh -c "echo 'Container user: \$(whoami)' && echo 'Container UID: \$(id -u)' && echo 'Container GID: \$(id -g)'"
```

### View Detailed Logs
```bash
# Look for disk space detection messages
docker logs palmr | grep -E "(🔍|📁|✅|❌|📋)"

# Look for mount point detection
docker logs palmr | grep -E "(📍|🎯|📋)"
```

### ❌ If Still Having Issues
1. **Check if Synology volumes are detected**:
   ```bash
   docker logs palmr | grep "Synology volumes detected"
   ```

2. **Verify directory permissions**:
   ```bash
   ls -la /volume1/docker/palmr/
   ```

3. **Check if ports are available**:
   ```bash
   netstat -tulpn | grep :5487
   ```

## 🔧 Alternative Configurations

### Single Volume Setup (Alternative)
If the 4-volume setup doesn't work, try this:

```yaml
version: '3.8'

services:
  palmr:
    image: kyantech/palmr:v3.1.1-rc.1
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=palmr-test-encryption-key-2025
      - PALMR_UID=1000 # UID for Synology NAS compatibility
      - PALMR_GID=1000 # GID for Synology NAS compatibility
    ports:
      - "5487:5487"
      - "3333:3333"
    volumes:
      - /volume1/docker/palmr:/app/server
    restart: unless-stopped
```

### Custom Volume Paths
If you need to use different volume paths:

```yaml
volumes:
  - /volume2/docker/palmr/uploads:/app/server/uploads
  - /volume2/docker/palmr/temp-uploads:/app/server/temp-uploads
  - /volume2/docker/palmr/temp-chunks:/app/server/temp-chunks
  - /volume2/docker/palmr/prisma:/app/server/prisma
```

If you have errors after all the configurations, please share the logs here so I can study it further and understand the problem. And if successful, let me know here too if you can.
