### ISSUE TITLE
Failed to upload file

### ISSUE THREAD

**Issue by bigdoug2005** [kyantech/Palmr#113]
[palmr.myserver.org-1751323219448.log](https://github.com/user-attachments/files/20988060/palmr.myserver.org-1751323219448.log)

I am getting a Failed To Upload File error. I have tried using both HTTP and HTTPS. I am using the default docker compose file and all I changed was the key.

![Image](https://github.com/user-attachments/assets/8e3d60fe-1dc2-4ece-bedf-b2bd232f8525)

services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=mykey # CHANGE THIS KEY FOR SECURITY
    ports:
      - "5487:5487" # Web port
      #- "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY)
    volumes:
      - palmr_data:/app/server # Volume for the application data (changed from /data to /app/server)
    restart: unless-stopped # Restart the container unless it is stopped

volumes:
  palmr_data:

**Comment by danielalves96** [comment]
It looks like you might be facing a file permission issue. Try running the container with UID and GID set to 1000, which usually matches the default user on most Linux systems.

Here’s an example Docker Compose configuration you can test:

```yaml
services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=mykey # Make sure to use a secure key with at least 32 characters in production
      - PALMR_UID=1000 # UID for container processes
      - PALMR_GID=1000 # GID for container processes
      - SECURE_SITE=false # Set to true if you're using a reverse proxy
    ports:
      - "5487:5487" # Web port
      # - "3333:3333" # API port (optional)
    volumes:
      - palmr_data:/app/server # Volume for application data
    restart: unless-stopped

volumes:
  palmr_data:
```
Test this setup and see if the file upload works now. Let me know if the issue persists!
