### ISSUE TITLE
[Error] Can't upload a file

### ISSUE THREAD

**Issue by PatAlcala9** [kyantech/Palmr#18]
I'm not sure if it's just me, but every time I try to upload a file, it gets refused.

When I check the Network Tools, it shows a method OPTIONS in red with CORS Failed. 

Double-clicking it, it reads: An error occurred: SSL_ERROR_RX_RECORD_TOO_LONG

Is my Docker Compose to blame here?

**Comment by danielalves96** [comment]
Hey! That error usually happens when the browser tries to connect to a service using **`HTTPS`**, but the service (in this case, MinIO) is actually serving **`HTTP`**.

If you just copied the docker-compose.yaml and ran it on your VPS, MinIO is running on port 6421 without SSL (plain HTTP). But your browser (or some proxy in between) is likely trying to reach it using `https://`, which causes the error:


```nginx
SSL_ERROR_RX_RECORD_TOO_LONG
```

That's also why you're seeing the CORS OPTIONS request fail, it's not really a CORS config issue, it's the SSL mismatch.

✅ Quick fix:

Open your .env file (or wherever you're setting environment variables) and make sure this is included:

```nginx
MINIO_USE_SSL=false
```

This tells the backend not to try HTTPS when connecting to MinIO internally.

Also, make sure you're not trying to access `https://<your-vps-ip>:6421` in your browser  use `http://<your-vps-ip>:6421 `instead, or go through your frontend.

Alternatively, you can set it to:

```nginx
MINIO_USE_SSL=true
```

If you’re planning to access MinIO securely over the internet (with HTTPS), you’ll need to either:

add SSL certificates to MinIO directly, or

put it behind a reverse proxy like Nginx or Traefik that handles HTTPS for you.

But for local or internal use, setting `MINIO_USE_SSL=false` should fix it.

Let me know if you need help setting up SSL later!

**Comment by danielalves96** [comment]
@PatAlcala9
If it works, please let me know what the problem is so I can improve the documentation.

**Comment by PunchEnergyFTW** [comment]
Hey! First of all, a big thank you for all the hard work you’ve put into this project.

I’m currently trying to run Palmr behind Bunkerweb, which acts as a reverse proxy (and does much more).

I've managed to log in, but I'm having trouble uploading files. When I check my browser’s developer console, I see that the browser tries to send a PUT request to my server on port 6421 (SERVER_IP:6421), which is the external port for MinIO.

To address this, I changed SERVER_IP to a domain name (`blob.mydomain.de`) that points to my reverse proxy. The proxy then forwards all requests to the MinIO container on port 6421, and I set MINIO_PORT to 443 because otherwise the browser would try to send a PUT request to `blob.mydomain.de:6421`.

Now, when I try to upload a file, the PUT request is sent to `blob.mydomain.de`. In the Palmr GUI, the upload reaches 100% but then fails. The PUT request receives a 403 (Forbidden) error.

![Image](https://github.com/user-attachments/assets/9a8c57a6-1b48-4814-8097-922a3eb625e2)

Manually opening blob.mydomain.de in my browser gets me a 307 answer and redirects to `blob.mydomain.de:6422`

My goal is to have all communication happen over HTTPS on port 443. However, I’m not fully sure how the upload process works.

My questions:
1. What exactly does the browser do during the upload?
2. Is it pushing the file to the original SERVER_IP:6421, and then making additional API calls to SERVER_IP:6422 once the upload is finished?
3. Is it possible to route all communication through the frontend’s FQDN on port 443 (In my case `fs.mydomain.de`)?
    I believe Next.js would then need to handle all the traffic, but I’m not sure if this is supported.

Below is my current docker-compose.yml and .env file setup:
- I added an external network belonging to my Bunkerweb reverse proxy so that i can forward traffic to the palmr stack. Port exposure on my host is (i think) not needed, since everything should happen internally or from external through bunkerweb into the internal docker network - however i didn't fully remove all exposed ports yet.

```yml
services:
  palmr-api:
    image: kyantech/palmr-api:v2.0.0-beta # Make sure to use the correct version (latest) of the image
    container_name: palmr-api
    depends_on:
      postgres:
        condition: "service_healthy"
      minio:
        condition: "service_healthy"
    environment:
      - PORT=${API_INTERNAL_PORT:-3333} # Port for the backend service
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgresRootPassword}@postgres:5432/palmr_db?schema=public # Database URL with configurable password through POSTGRES_PASSWORD env var
      - MINIO_ENDPOINT=blob.mydomain.de # This can change if your MinIO is at a different address
      - MINIO_PORT=443 # Default MinIO port (Change if yours is not the default)
      - MINIO_USE_SSL=false # MinIO uses SSL by default, but you can change it to true if needed
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio_root_user} # MinIO credentials can be configured through MINIO_ROOT_USER env vars
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioRootPassword} # MinIO credentials can be configured through MINIO_ROOT_PASSWORD env vars
      - MINIO_REGION=sa-east-1 # MinIO region - This is needed for MinIO to work properly
      - MINIO_BUCKET_NAME=files # MinIO bucket name - This is needed for MinIO to work properly, dont change it if you don't know what you are doing
      - FRONTEND_URL=${APP_URL:-http://${SERVER_IP:-localhost}:${APP_EXTERNAL_PORT:-5487} # Frontend URL - Make sure to use the correct frontend URL, depends on where the frontend is running, its prepared for localhost, but you can change it to your frontend URL if needed
      - SERVER_IP=blob.mydomain.de # Server IP - Make sure to use the correct server IP if you running on a cloud provider or a virtual machine. This prepared for localhost, but you can change it to your server IP if needed
    ports:
      - "${API_EXTERNAL_PORT:-3333}:${API_INTERNAL_PORT:-3333}" # Backend port mapping
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_INTERNAL_PORT:-3333}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - bw-services

  palmr-app:
    image: kyantech/palmr-app:v2.0.0-beta # Make sure to use the correct version (latest) of the image
    container_name: palmr-web
    depends_on:
      palmr-api:
        condition: "service_healthy"
    ports:
      - "${APP_EXTERNAL_PORT:-5487}:5487" # Frontend port mapping
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - API_BASE_URL=http://palmr-api:${API_INTERNAL_PORT:-3333} # Here we use docker's internal network to reference the backend service (can be changed if needed)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5487"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bw-services

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z # Use only version RELEASE.2025-03-12T18-04-18Z to avoid compatibility issues with the backend
    container_name: minio
    environment:
      # MinIO credentials - same as above, configurable through environment variables
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio_root_user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioRootPassword}
      - MINIO_SITE_REGION=sa-east-1
    command: server /data --address ":${MINIO_INTERNAL_API_PORT:-6421}" --console-address ":${MINIO_INTERNAL_CONSOLE_PORT:-6422}"
    volumes:
      - /opt/docker/palmr/minio:/data
    expose:
      - ${MINIO_INTERNAL_API_PORT:-6421}
      - ${MINIO_INTERNAL_CONSOLE_PORT:-6422}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_INTERNAL_API_PORT:-6421}/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bw-services

  minio-init:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z # Use only version RELEASE.2025-03-12T17-29-24Z to avoid compatibility issues with the backend and MinIO
    container_name: minio-init
    depends_on:
      minio:
        condition: "service_healthy"
    restart: "no"
    # The entrypoint script will create a bucket called "files" and set it to be publicly readable using the MinIO client (mc).
    entrypoint: >
      sh -c "
        sleep 5 &&
        mc alias set myminio http://minio:${MINIO_INTERNAL_API_PORT:-6421} ${MINIO_ROOT_USER:-minio_root_user} ${MINIO_ROOT_PASSWORD:-minioRootPassword} &&
        mc mb myminio/files --ignore-existing &&
        mc anonymous set download myminio/files
      "
    networks:
      - bw-services

  postgres:
    image: bitnami/postgresql:17.2.0 # You can use any postgres version you prefer, but remember that some versions might not be compatible
    container_name: palmr-postgres
    environment:
      # PostgreSQL credentials configurable through environment variables
      # POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB can be set to override defaults
      - POSTGRESQL_USERNAME=${POSTGRES_USER:-postgres}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-postgresRootPassword}
      - POSTGRESQL_DATABASE=${POSTGRES_DB:-palmr_db}
    volumes:
      - /opt/docker/palmr/postgres:/bitnami/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "palmr"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bw-services
networks:
  bw-services:
    external: true
```


And here my .env file

```yml
POSTGRES_PASSWORD=pass
APP_URL=http://fs.mydomain.de
MINIO_ROOT_USER=abcd
MINIO_ROOT_PASSWORD=pass
MINIO_EXTERNAL_API_PORT=443

```

**Comment by danielalves96** [comment]
@PunchEnergyFTW 

Just to clarify a doubt, are you running any services with https? Or all with http?

I ask because I was recently running tests on my VPS and had the problem using my frontend in https, but with all services in http and the env var MINIO_USE_SSL=false I was able to run it successfully. Initially I recommend running everything with http only, if it is with https, the upload will be blocked by minio until you have valid ssl certificates. I am still investigating all error cases to improve the documentation, and to anticipate any and all types of obstacles that may be faced.
Since I still don't know exactly what the error is, could you upload each compose service and test them independently and share them here with me? This helped me solve previous problems in development.

On my VPS:
https://github.com/user-attachments/assets/c91a7770-ea6f-4bd0-869c-c00dfc71ddf5

**Comment by PunchEnergyFTW** [comment]
@danielalves96 i am trying to run everything over HTTPS

I think i got it running. Although shared links wont work. I am still investigating that.

Just a quick rundown, i have two FQDNs
`blob.mydomain.com` -> Connection to Minio
`palmr.mydomain.com` -> Connection to Frontend
***BOTH DNS entries resolve to the VPS's public IP***

In order to get all of this working, getting rid of CORS Errors etc, minio must be running on port 443 (when using HTTPS with a separate domain for minio like `blob.mydomain.com`.

## `.env file`
```yaml
#Minio must communicate over HTTPS to work with my domain `blob.mydomain.com`:
MINIO_INTERNAL_API_PORT=443`
MINIO_EXTERNAL_API_PORT=443
SERVER_IP=blob.mydomain.com

#I want to access the frontend via palmr.mydomain.com:
APP_URL=https://palmr.mydomain.com

#MISC - not relevant for this problem
POSTGRES_PASSWORD=pass
MINIO_ROOT_USER=abcd
MINIO_ROOT_PASSWORD=password
```

## Changes I've made in the docker-compose.yml
```yaml
services:
  palmr-api:
  # You might be wondering what this "proxy" network is about - I've added this section to ALL containers in this docker-compose.yml and my reverse proxy is within the same network. I can ping all Containers from my proxy with their container-name
    networks:
      - proxy
    [...]
    environment:
      - MINIO_ENDPOINT=${SERVER_IP:-localhost} # Had to change this to SERVER_IP, otherwise file deletion wouldn't work
      - MINIO_USE_SSL=true # Since I am using HTTPS, set this to true
    # OLD 
    # - FRONTEND_URL=${APP_URL:-http://${SERVER_IP:-localhost}:${APP_EXTERNAL_PORT:-5487}}
      - FRONTEND_URL=${APP_URL:-http://${SERVER_IP:-localhost}:${APP_EXTERNAL_PORT:-5487} # Removed the last bracket - otherwise I would get INVALID URL errors in the palmr-api container...
[...]
  minio:
  # You might be wondering what this "proxy" network is about - I've added this section to ALL containers in this docker-compose.yml and my reverse proxy is within the same network. I can ping all Containers from my proxy with their container-name
    networks:
      - proxy
    [...]
  # OLD
  # ports:
  #     - "${MINIO_EXTERNAL_API_PORT:-6421}:${MINIO_INTERNAL_API_PORT:-6421}"
  #     - "${MINIO_EXTERNAL_CONSOLE_PORT:-6422}:${MINIO_INTERNAL_CONSOLE_PORT:-6422}"
  # I am using a reverse Proxy on the same host, this proxy is already listening on port 443 so i cannot expose this container on port 443 aswell. Therefore I only configured the container to expose the ports within the docker network.
    expose:
      - "${MINIO_INTERNAL_API_PORT:-6421}"
      - "${MINIO_INTERNAL_CONSOLE_PORT:-6422}"
[...]

# Adding the proxy network for my reverse proxy system
networks:
  proxy:
    external: true
# End of File
```

## Proxy Configuration
Point your reverse proxy for:
- `palmr.mydomain.com` to `http://palmr-app:5487`
- `blob.mydomain.com` to `http://minio:443`
#### Where do these Names (minio, palmr-app) come from?
Since all containers and my reverse proxy container are within the same network called `proxy` the docker internal DNS can resolve the container names to their respective IPs

**Comment by PunchEnergyFTW** [comment]
@danielalves96 i am trying to run everything over HTTPS

I think i got it running. Although shared links wont work. I am still investigating that.

Just a quick rundown, i have two FQDNs
`blob.mydomain.com` -> Connection to Minio
`palmr.mydomain.com` -> Connection to Frontend
***BOTH DNS entries resolve to the VPS's public IP***

In order to get all of this working, getting rid of CORS Errors etc, minio must be running on port 443 (when using HTTPS with a separate domain for minio like `blob.mydomain.com`.

## `.env file`
```yaml
#Minio must communicate over HTTPS to work with my domain `blob.mydomain.com`:
MINIO_INTERNAL_API_PORT=443
MINIO_EXTERNAL_API_PORT=443
SERVER_IP=blob.mydomain.com

#I want to access the frontend via palmr.mydomain.com:
APP_URL=https://palmr.mydomain.com

#MISC - not relevant for this problem
POSTGRES_PASSWORD=pass
MINIO_ROOT_USER=abcd
MINIO_ROOT_PASSWORD=password
```

## Changes I've made in the docker-compose.yml
```yaml
services:
  palmr-api:
  # You might be wondering what this "proxy" network is about - I've added this section to ALL containers in this docker-compose.yml and my reverse proxy is within the same network. I can ping all Containers from my proxy with their container-name
    networks:
      - proxy
    [...]
    environment:
      - MINIO_ENDPOINT=${SERVER_IP:-localhost} # Had to change this to SERVER_IP, otherwise file deletion wouldn't work
      - MINIO_USE_SSL=true # Since I am using HTTPS, set this to true
    # OLD 
    # - FRONTEND_URL=${APP_URL:-http://${SERVER_IP:-localhost}:${APP_EXTERNAL_PORT:-5487}}
      - FRONTEND_URL=${APP_URL:-http://${SERVER_IP:-localhost}:${APP_EXTERNAL_PORT:-5487} # Removed the last bracket - otherwise I would get INVALID URL errors in the palmr-api container...
[...]
  minio:
  # You might be wondering what this "proxy" network is about - I've added this section to ALL containers in this docker-compose.yml and my reverse proxy is within the same network. I can ping all Containers from my proxy with their container-name
    networks:
      - proxy
    [...]
  # OLD
  # ports:
  #     - "${MINIO_EXTERNAL_API_PORT:-6421}:${MINIO_INTERNAL_API_PORT:-6421}"
  #     - "${MINIO_EXTERNAL_CONSOLE_PORT:-6422}:${MINIO_INTERNAL_CONSOLE_PORT:-6422}"
  # I am using a reverse Proxy on the same host, this proxy is already listening on port 443 so i cannot expose this container on port 443 aswell. Therefore I only configured the container to expose the ports within the docker network.
    expose:
      - "${MINIO_INTERNAL_API_PORT:-6421}"
      - "${MINIO_INTERNAL_CONSOLE_PORT:-6422}"
[...]

# Adding the proxy network for my reverse proxy system
networks:
  proxy:
    external: true
# End of File
```
### Full docker-compose.yml

[docker-compose.txt](https://github.com/user-attachments/files/19915965/docker-compose.txt)

## Proxy Configuration
Point your reverse proxy for:
- `palmr.mydomain.com` to `http://palmr-web:5487`
- `blob.mydomain.com` to `http://minio:443`
#### Where do these Names (minio, palmr-web) come from?
Since all containers and my reverse proxy container are within the same network called `proxy` the docker internal DNS can resolve the container names to their respective IPs





# Shared links broken
Currently i am still having the problem that shared links won't work. I'll have to run the app in dev mode to debug it i guess.
```bash
palmr-web     |  ⨯ [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
palmr-web     |   digest: '1793599260'
palmr-web     | }
```

![Image](https://github.com/user-attachments/assets/d11eefd5-a2da-46e2-917a-1ca8889ba237)

**Comment by danielalves96** [comment]
@PunchEnergyFTW 

Perfect!! I can take a look at the code later and respond to your question.

But I can tell you in advance that the issue with the shared link was due to a build break in Docker. I’ve already fixed it and pushed a new latest image that resolves this. To get it working, just delete your `palmr-app:latest` image from server and pull it again from the Docker hub, where everything is working now.

And thank you so much for sharing the detailed installation process, it’s going to help a lot!

If everything works, please let me know here!

**Comment by PunchEnergyFTW** [comment]
@danielalves96 

I've just pulled the new image and deployed it. 

Everything works now! Perfect 💯

**Comment by PatAlcala9** [comment]
I was able to get it to work through **MINIO_USE_SSL=false**, but I had to disable the frontend's SSL as well.

If I don't and use **MINIO_USE_SSL=true** with it, for some reason, it doesn't work. But I think that's on me, I think my nginx config for my server's IP was to blame. I couldn't get the Minio's server IP to work with SSL without a proper domain name. And since SERVER_IP do require an IP address and not a domain, I was stuck, and so I avoided this approach.

I have to stick with **MINIO_USE_SSL=false** and http frontend. But another problem arise - I can't share the uploaded file. The generated sharing link doesn't work.

**Comment by danielalves96** [comment]
Hey @PatAlcala9 

Right! The approach is the same, for everything to work with SSL (https) or minio you need to have a valid certificate as well. For me it is difficult to document the entire process because each person uses a specific way to configure SSL and there are several ways to do this, in this case you will have to know each one on your own server.

The shared link was due to a build break in Docker. I’ve already fixed it and pushed a new latest image that resolves this. To get it working, just delete your `palmr-app:latest` image from server and **pull it again from the Docker hub**, where everything is working now.

@PunchEnergyFTW successfully pulled the project and got the share link working. He also found a way to run it with HTTPS using a reverse proxy, so if you ever need HTTPS, it might be a good idea to chat with him about it.

**Comment by PunchEnergyFTW** [comment]
> I was able to get it to work through **MINIO_USE_SSL=false**, but I had to disable the frontend's SSL as well.
> 
> If I don't and use **MINIO_USE_SSL=true** with it, for some reason, it doesn't work. But I think that's on me, I think my nginx config for my server's IP was to blame. I couldn't get the Minio's server IP to work with SSL without a proper domain name. And since SERVER_IP do require an IP address and not a domain, I was stuck, and so I avoided this approach.
> 
> I have to stick with **MINIO_USE_SSL=false** and http frontend. But another problem arise - I can't share the uploaded file. The generated sharing link doesn't work.

@PatAlcala9 
Please refer to my earlier response in this thread. The SERVER_IP value can be a domain name-just make sure it’s a different domain, such as blob.example.com. Also, remember to specify it without including https:// at the beginning.

There’s a caveat: if you’re running a standalone NGINX instance (not in a container), you won’t be able to communicate with MinIO over port 443, since both services would need to listen on the same port, and Docker cannot expose port 443 if your local NGINX is already using it.

To resolve this, consider running your NGINX instance inside Docker as well. This way, MinIO can listen on port 443 within the Docker network, avoiding any port conflicts. I plan to create a sample docker-compose.yml file using Traefik as a reverse proxy and will share it here in the next few days.

By the way, are you using self-signed certificates or publicly signed certificates (such as those from Let’s Encrypt)?

**Comment by PunchEnergyFTW** [comment]
@PatAlcala9  
Here's a working docker-compose.yml with .env and config files for NGINX.
https://github.com/PunchEnergyFTW/palmr_deployment_examples

**Comment by mariushosting** [comment]
I got the following when try to upload a simple file. @danielalves96 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6422/files/cmai0v9m90000oa5boferim3b/1746870328139-B7QCQJ8vxSvP.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=miniouser%2F20250510%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250510T094528Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=58af07baa18a619502398c100d51dbbdfceda0835bcfdf8cea38fb4959f77cf7. (Reason: CORS request did not succeed). Status code: (null).

**Comment by PunchEnergyFTW** [comment]
> I got the following when try to upload a simple file. [@danielalves96](https://github.com/danielalves96)
> 
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6422/files/cmai0v9m90000oa5boferim3b/1746870328139-B7QCQJ8vxSvP.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=miniouser%2F20250510%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250510T094528Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=58af07baa18a619502398c100d51dbbdfceda0835bcfdf8cea38fb4959f77cf7. (Reason: CORS request did not succeed). Status code: (null).


Can you please explain what your setup is? Are you using HTTPS? Localhost or a domain?

**Comment by mariushosting** [comment]
> > I got the following when try to upload a simple file. [@danielalves96](https://github.com/danielalves96)
> > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6422/files/cmai0v9m90000oa5boferim3b/1746870328139-B7QCQJ8vxSvP.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=miniouser%2F20250510%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250510T094528Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=58af07baa18a619502398c100d51dbbdfceda0835bcfdf8cea38fb4959f77cf7. (Reason: CORS request did not succeed). Status code: (null).
> 
> Can you please explain what your setup is? Are you using HTTPS? Localhost or a domain?

https with the reverse proxy.

**Comment by PunchEnergyFTW** [comment]
> > > I got the following when try to upload a simple file. [@danielalves96](https://github.com/danielalves96)
> > > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6422/files/cmai0v9m90000oa5boferim3b/1746870328139-B7QCQJ8vxSvP.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=miniouser%2F20250510%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250510T094528Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=58af07baa18a619502398c100d51dbbdfceda0835bcfdf8cea38fb4959f77cf7. (Reason: CORS request did not succeed). Status code: (null).
> > 
> > Can you please explain what your setup is? Are you using HTTPS? Localhost or a domain?
> 
> https with the reverse proxy.

So your Frontend is https://your.domain.com?
Did you proxy the Backend Minio as well? The Frontend currently redirects you to localhost, I believe your minio instance isn't running locally on your machine.

Have a look at my example deployments:
https://github.com/PunchEnergyFTW/palmr_deployment_examples

**Comment by mariushosting** [comment]
> > > > I got the following when try to upload a simple file. [@danielalves96](https://github.com/danielalves96)
> > > > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6422/files/cmai0v9m90000oa5boferim3b/1746870328139-B7QCQJ8vxSvP.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=miniouser%2F20250510%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250510T094528Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=58af07baa18a619502398c100d51dbbdfceda0835bcfdf8cea38fb4959f77cf7. (Reason: CORS request did not succeed). Status code: (null).
> > > 
> > > 
> > > Can you please explain what your setup is? Are you using HTTPS? Localhost or a domain?
> > 
> > 
> > https with the reverse proxy.
> 
> So your Frontend is https://your.domain.com? Did you proxy the Backend Minio as well? The Frontend currently redirects you to localhost, I believe your minio instance isn't running locally on your machine.
> 
> Have a look at my example deployments: https://github.com/PunchEnergyFTW/palmr_deployment_examples

Minio is locally hosted.

I also try to proxy minio as well but this does not work at all.

Here is my compose: https://docker.mariushosting.com/mariushosting/a3e808055f2544eea5c0a5fe347952e2

**Comment by PunchEnergyFTW** [comment]
@mariushosting 

Do you use a containerized reverse proxy? What exactly didn't work with the reverse proxy for minio?

**Comment by mariushosting** [comment]
> [@mariushosting](https://github.com/mariushosting)
> 
> Do you use a containerized reverse proxy? What exactly didn't work with the reverse proxy for minio?

No. I use Synology NAS and I have a lot of experience with Docker https://mariushosting.com/docker/
Minio is working in Reverse Proxy, Palmr is working in Reverse Prox only the image upload is not working.

Whenever I try to upload an image on Palmr I get this Cors Error in the logs.

**Comment by PunchEnergyFTW** [comment]
Try setting the SERVER_IP to the FQDN of your minio instance instead of `localhost`
`SERVER_IP=blob.mydomain.com`

**Comment by mariushosting** [comment]
> [@mariushosting](https://github.com/mariushosting)
> 
> Do you use a containerized reverse proxy? What exactly didn't work with the reverse proxy for minio?

The server let me only to add SERVER_IP on the following format on environment

SERVER_IP: minio.mariushosting.synology.me

and I get the following if I try to upload file:

7164-ee8ac980da9e3780.js:1 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
8893-b0b83af24604ce3f.js:1 Mixed Content: The page at 'https://palmr.mariushosting.synology.me/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://minio.mariushosting.synology.me:6421/files/cmaihifxu0000p95axebuzpn5…Signature=0114802…'. This request has been blocked; the content must be served over HTTPS.

After that

If I add on the following format:

SERVER_IP: https://minio.mariushosting.synology.me

I get this error on logs: 
InvalidEndpointError: Invalid endPoint : https://minio.mariushosting.synology.me

    at new TypedClient (/app/server/node_modules/.pnpm/minio@8.0.4/node_modules/minio/dist/main/internal/client.js:64:13)

    at new Client (/app/server/node_modules/.pnpm/minio@8.0.4/node_modules/minio/dist/main/minio.js:61:1)

    at Object.<anonymous> (/app/server/dist/config/minio.config.local.js:6:28)

    at Module._compile (node:internal/modules/cjs/loader:1364:14)

    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

    at Module.load (node:internal/modules/cjs/loader:1203:32)

    at Module._load (node:internal/modules/cjs/loader:1019:12)

    at Module.require (node:internal/modules/cjs/loader:1231:19)

    at require (node:internal/modules/helpers:177:18)

    at Object.<anonymous> (/app/server/dist/modules/file/service.js:5:30)

Node.js v18.20.8

 ELIFECYCLE  Command failed with exit code 1.

**Comment by PunchEnergyFTW** [comment]
You're on the right track. Currently the palmr frontent generates a url with the port :6421
MinIO must be listening on port 443, internally and externally. I don't know your setup and if that is possible since only one process can bind to port 443.

`SERVER_IP: minio.mariushosting.synology.me` is correct, you don't need `https://`

If this is not possible in your current setup, i'll have to rewrite the code to support this in another way.

**Comment by mariushosting** [comment]
Yes I don't think this works on a Synology NAS or other NAS devices at all. Maybe if this helps: https://github.com/stonith404/pingvin-share this similar project works very well. Thank you for the support @PunchEnergyFTW 

> You're on the right track. Currently the palmr frontent generates a url with the port :6421 MinIO must be listening on port 443, internally and externally. I don't know your setup and if that is possible since only one process can bind to port 443.
> 
> `SERVER_IP: minio.mariushosting.synology.me` is correct, you don't need `https://`
> 
> If this is not possible in your current setup, i'll have to rewrite the code to support this in another way.

**Comment by PunchEnergyFTW** [comment]
@mariushosting 

I was being stupid, i came home and played around a little. Of course you can host Minio on another port and still use SSL. Just make sure that you set these Variables in the `palmr-api` container:
`MINIO_APP_URL=blob.mydomain.com` -> URL of your FQDN to Minio
```yml
  palmr-api:                                       
    environment:                                   
       - MINIO_USE_SSL=true
       - MINIO_ENDPOINT=${MINIO_APP_URL:-localhost} 
```
And make sure that the Minio container listens on port 443 *only* internally.
```yml
MINIO_EXTERNAL_API_PORT=6421
MINIO_INTERNAL_API_PORT=443
```

Your reverse proxy can then route traffic to `http://localhost:6421`

This setup worked for me. Let me know if it works for you too.

**Comment by mariushosting** [comment]
> [@mariushosting](https://github.com/mariushosting)
> 
> I was being stupid, i came home and played around a little. Of course you can host Minio on another port and still use SSL. Just make sure that you set these Variables in the `palmr-api` container: `MINIO_APP_URL=blob.mydomain.com` -> URL of your FQDN to Minio
> 
>   palmr-api:                                       
>     environment:                                   
>        - MINIO_USE_SSL=true
>        - MINIO_ENDPOINT=${MINIO_APP_URL:-localhost} 
> And make sure that the Minio container listens on port 443 _only_ internally.
> 
> MINIO_EXTERNAL_API_PORT=6421
> MINIO_INTERNAL_API_PORT=443
> Your reverse proxy can then route traffic to `http://localhost:6421`
> 
> This setup worked for me. Let me know if it works for you too.

Added it to the letter but unfortunately nothing works.

![Image](https://github.com/user-attachments/assets/f58b4284-e108-41b5-9a97-d75b27ab0a9a)

**Comment by PunchEnergyFTW** [comment]
@mariushosting 

It seems like the Palmr frontend is still generating a url with port :6421
Make sure that the `MINIO_INTERNAL_API_PORT` for the minio container is 443

Since you're not using the env vars in your yml, change the occurences manually.

```yml
  minio:
  [...]
    command: server /data --console-address :443 --console-address :6422 # -> change port to 443
    [...]
    ports:
      - 6421:443 # -> Change internal port to 443
      - 6422:6422
```

And on the palmr-api container as well:
```yml
  palmr-api:
  [...]
    environment:
       MINIO_PORT: 443
```
