### ISSUE TITLE
Permission issues with bind-mounted data directory in Palmr Docker container

### ISSUE THREAD

**Issue by baldemar-wuda** [kyantech/Palmr#45]
I've deployed the latest version of Palmr and encountered a problem when using a bind-mounted directory for data storage (e.g., /volume1/docker/palmr/data). The container runs under user with UID 1001 and GID 65533 (nogroup). On my host system UID 1001 is assigned to a different user, and the group ownership of the data directory differs from the container’s group.

As a result, despite setting folder permissions to 777, the application fails to start properly due to access issues on the mounted directory. Changing the directory ownership on the host to UID 1001 and GID 65533 resolves the problem.

Suggestions to improve compatibility:
Provide environment variables to configure the UID and GID the container runs under, allowing users to match permissions with their host system.

**Comment by danielalves96** [comment]
@baldemar-wuda 

I've been looking into your case. I'm already preparing a new build to accept environment variables for these settings. Thanks for pointing it out.

**Comment by danielalves96** [comment]
#56

**Comment by danielalves96** [comment]
Hey @baldemar-wuda!

I've developed a feature in Release #57 that allows you to configure GID and UID through environment variables. I've also added the documentation here: [docs](https://palmr.kyantech.com.br/docs/3.0-beta/uid-gid-configuration).

Could you please test this out and let me know if it resolves the issue you're facing? Once confirmed, we can finalize this issue.

> To get the updates, remember to pull the `latest` image of Palmr. from Docker, or use the specific version `v3.0.0-beta.1` in your docker-compose file.

**Comment by ase1590** [comment]
OS: Arch Linux
Docker version 28.2.2
docker compose version 2.37.1

I am seeing this in the docker logs:
```
palmr  | Runtime UID/GID configuration detected: UID=1000, GID=100
palmr  | Adjusting user/group IDs from 1001:1001 to 1000:100
palmr  | Using existing group with GID 100: users
palmr  | Warning: Could not change user group
palmr  | Warning: UID 1000 already exists as user 'node'
palmr  | Container will continue but may have permission issues
```
server.err.log shows
```
node:internal/modules/cjs/loader:1215
  throw err;
  ^

Error: Cannot find module '/app/server/dist/server.js'
```
Which I assume is just permissions related again. 

using this for composefile for local testing:

```yaml
services:
  palmr:
    image: kyantech/palmr:v3.0.0-beta.1
    restart: unless-stopped # Restart the container unless it is stopped
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
      - PALMR_UID=1000
      - PALMR_GID=100
    ports:
      - "5487:5487" # Web port
     # - "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY)
    volumes:
      - ./palmr_data:/app/server # Volume for the application data
```
runs fine using normal docker volumes without the plmr_uid/gid vars, just not via bind mount with them.
