### ISSUE TITLE
Crash when using bind mounts

### ISSUE THREAD

**Issue by PietHelzel** [kyantech/Palmr#47]
When deploying the program using this compose file with podman compose:

```yaml
services:
  palmr:
    image: docker.io/kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
    ports:
      - "5487:5487" # Web port
    volumes:
      - ./data:/app/server # Volume for the application data
```

I get the following log (command: podman compose logs):

```
[palmr] | Starting Palmr Application...
[palmr] | Storage Mode: false
[palmr] | Database: SQLite
[palmr] | /usr/lib/python3.12/site-packages/supervisor/options.py:13: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
[palmr] |   import pkg_resources
[palmr] | 2025-06-13 20:27:40,446 INFO Set uid to user 0 succeeded
[palmr] | 2025-06-13 20:27:40,447 INFO supervisord started with pid 1
[palmr] | 2025-06-13 20:27:41,452 INFO spawned: 'server' with pid 5
[palmr] | 2025-06-13 20:27:41,454 INFO spawned: 'web' with pid 6
[palmr] | 2025-06-13 20:27:42,462 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[palmr] | 2025-06-13 20:27:51,496 INFO success: web entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
[palmr] | 2025-06-13 20:27:56,802 WARN exited: server (exit status 1; not expected)
[palmr] | 2025-06-13 20:27:57,512 INFO spawned: 'server' with pid 173
[palmr] | 2025-06-13 20:27:58,516 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[palmr] | 2025-06-13 20:28:03,356 WARN exited: server (exit status 1; not expected)
[palmr] | 2025-06-13 20:28:03,537 INFO spawned: 'server' with pid 289
[palmr] | 2025-06-13 20:28:04,543 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[palmr] | 2025-06-13 20:28:09,384 WARN exited: server (exit status 1; not expected)
[palmr] | 2025-06-13 20:28:09,560 INFO spawned: 'server' with pid 405
```

It seems like the server process keeps crashing and restarting. If there is any way to get more detailed debug information, please let me know!

Thanks in advance

**Comment by danielalves96** [comment]
@PietHelzel 

The Palmr application uses supervisor to manage processes. The actual error messages are stored in specific log files inside the container.

### Access Supervisor Logs

```bash
# Check server error logs (most important - shows why it's crashing)
podman exec palmr cat /var/log/supervisor/server.err.log

# Check server output logs
podman exec palmr cat /var/log/supervisor/server.out.log

# Check general supervisor logs
podman exec palmr cat /var/log/supervisor/supervisord.log

# Check web application logs (if needed)
podman exec palmr cat /var/log/supervisor/web.err.log
```

### Monitor Logs in Real-time

```bash
# Watch logs as they happen
podman exec palmr tail -f /var/log/supervisor/server.err.log

# Or watch all container logs
podman compose logs -f palmr
```

Kindly test this and let me know if you were able to identify the error that appears in the logs, and whether the log commands are working properly.

I haven’t run any tests using Podman yet — only Docker.
Let’s figure this out and get it fixed!

**Comment by PietHelzel** [comment]
Thanks for the fast response.

server.err.log:

```
Node.js v20.19.2
Warning: [Prisma auto-install on generate] Prisma could not find a package.json file in the inferred project root /app/server. During the next step, when an auto-install of Prisma package(s) will be attempted, it will then be created by your package manager on the appropriate level if necessary.
Error: Command failed with exit code 243: npm i prisma@6.9.0 -D --silent
Warning: [Prisma auto-install on generate] Prisma could not find a package.json file in the inferred project root /app/server. During the next step, when an auto-install of Prisma package(s) will be attempted, it will then be created by your package manager on the appropriate level if necessary.
Error: Command failed with exit code 243: npm i prisma@6.9.0 -D --silent
node:internal/modules/cjs/loader:1215
  throw err;
  ^

Error: Cannot find module '@prisma/client'
Require stack:
- /app/server/prisma/seed.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/app/server/prisma/seed.js:2:26)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/server/prisma/seed.js' ]
}

Node.js v20.19.2
node:internal/modules/cjs/loader:1215
  throw err;
  ^

Error: Cannot find module '/app/server/dist/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

The other log files don't seem to contain anything interesting.

**Comment by graphixillusion** [comment]
I'm getting the exact same error with docker

**Comment by gbomacfly** [comment]
same here

**Comment by danielalves96** [comment]
@PietHelzel @graphixillusion @gbomacfly 

Please, try execute with this compose:

```yaml
services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars
    ports:
      - "5487:5487"
      - "3333:3333"
    volumes:
      - palmr_uploads:/app/server/uploads
      - palmr_chunks:/app/server/temp-chunks
      - palmr_database:/app/server/prisma
    restart: unless-stopped

volumes:
  palmr_uploads:
  palmr_chunks:
  palmr_database:

```

> Remember to remove the previously created volume:
`docker volume rm palmr_data`

After testing please let me know if it works or not..

**Comment by PietHelzel** [comment]
Ah, I found what actually causes this issue for me: It works just fine using a named volume, but not a bind mount. It also works just using a single volume for /app/server. Any clue why this could be the case? Maybe some permission issue or something?

**Comment by graphixillusion** [comment]
@danielalves96 still not working here: same error. Yep i'm using bind mount too, not named volumes

**Comment by Nasus20202** [comment]
I've the same issue while trying to deploy it to the RKE2 cluster so it's not a podman/docker only issue.

**Comment by danielalves96** [comment]
@PietHelzel 
I'm trying to figure out why here! But I haven't found the problem yet.
Could you share your compose here with us?

**Comment by PietHelzel** [comment]
Not working:

```yaml
services:
  palmr:
    image: docker.io/kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
    ports:
      - "5487:5487" # Web port
    volumes:
      - ./data:/app/server # Volume for the application data
```

Working:

```yaml
services:
  palmr:
    image: docker.io/kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
    ports:
      - "5487:5487" # Web port
    volumes:
      - palmr-data:/app/server # Volume for the application data
volumes:
  palmr-data:

```

**Comment by PietHelzel** [comment]
I have also tested this with v2.0.0-beta.6, and it starts fine there using bind mounts.

**Comment by Nasus20202** [comment]
From what I've observed, mounting a local directory overwrites data that is shipped in the image. Mounting a new named volume copies the existing data.

**Comment by danielalves96** [comment]
@PietHelzel Just one question that came to mind here... in the documentation, are we using the version of docker compose that works, correct?

https://palmr.kyantech.com.br/docs/3.0-beta/quick-start#exploring-the-docker-composeyaml-file

**Comment by PietHelzel** [comment]
Yes, that is the case 👍 I run all my containers using bind mounts though to keep the volumes next to the compose file, and it has always worked for other services so far.

**Comment by Nasus20202** [comment]
That would also explain my issues on K8s since PV is always empty when created.

**Comment by PietHelzel** [comment]
> From what I've observed, mounting a local directory overwrites data that is shipped in the image. Mounting a new named volume copies the existing data.

Did a tiny bit of research and that seems to be the way it is supposed to work 👍 I guess all other services I have tried do not need any files to be copied over from the image, or do it manually.

**Comment by danielalves96** [comment]
@PietHelzel @graphixillusion @Nasus20202 
Analyzing the issue as a whole, it seems that the problem is the same as the one mentioned in #45 , If that is the problem, I will close this issue to centralize everything in one. Realmente parece algo relacionado a permissão. Já estou atualizando a build para permitir configuração. It really seems like something related to permission. I'm already updating the build to allow configuration.

**Comment by PietHelzel** [comment]
I don't think these are the same. This isn't a permission issue, it is the fact that using a bind mount clears the data from the container image. From the dockerfile (just an example):

```dockerfile
COPY --from=server-builder --chown=palmr:nodejs /app/server/dist ./dist
COPY --from=server-builder --chown=palmr:nodejs /app/server/node_modules ./node_modules
COPY --from=server-builder --chown=palmr:nodejs /app/server/prisma ./prisma
COPY --from=server-builder --chown=palmr:nodejs /app/server/package.json ./
```

When bind mounting the volume /app/server, all that data is deleted again. This IS INTENDED it seems. However, other containers I have used seem to have a solution for this which is not affected.

**Comment by Nasus20202** [comment]
We shouldn't rely on that automatic copying of data. It is a Docker specific implementation and also it happens only for new volumes. I would suggest changing the location of all data that should be stored on an external volume to another directory. Also there is no need to place the node_modules in the volume :)

**Comment by gbomacfly** [comment]
I have found a solution for me.
Start the container with one named volume (- palmr-data:/app/server). Stop the container, copy the contents of the volume to ./data, switch to bind mount (- ./data:/app/server) in docker-compose.yml and restart. 
Works fine :)

**Comment by clbx** [comment]
This breaks on Kubernetes (or any container platform where a mount overwrites the directory its mounted to, like docker bind-mounts). Both the quickstart guide and the setup where you have the 3 split out volumes fail. The first due to the issue from OP and then the second palmr expects the database to be pre-populated.

Putting data in volumes that are expected to be mounted is generally considered a bad practice. I ended up creating an init-container that just copies all the files in on the first deployment, but re-designing the volumes in a way that it doesn't expect it to be pre-populated would be a great improvement to see.

**Comment by graphixillusion** [comment]
> I have found a solution for me. Start the container with one named volume (- palmr-data:/app/server). Stop the container, copy the contents of the volume to ./data, switch to bind mount (- ./data:/app/server) in docker-compose.yml and restart. Works fine :)

This is working indeed but i have found another issue with this config: despite the bind mount in your ./data folder, when you upload something, palmr still autocreates named volumes with random names inside /var/lib/docker/volumes/... and all the files you upload are stored overe there (in encrypted form as they should be). I think we should have the option to have these uploads in the same bind's mount specified in docker-compose file (in this case ./data)

**Comment by ekadin-mtc** [comment]
Having the same issue here in Kubernetes. My workaround was to utilize subPaths
```
volumeMounts:
          - name: palmr-data
            mountPath: /app/server/prisma
            subPath: prisma
          - name: palmr-data
            mountPath: /app/server/uploads
            subPath: uploads
      volumes:
        - name: palmr-data
          persistentVolumeClaim:
            claimName: palmr-claim
```

I also needed to prepopulate the prisma directory with [schema.prisma and seed.js](https://github.com/kyantech/Palmr/tree/main/apps/server/prisma)
