### ISSUE TITLE
Not using S3 with ENABLE_S3 set

### ISSUE THREAD

**Issue by clbx** [kyantech/Palmr#50]
I have the following docker compose to connect Palmr to my MinIO instance, configured using [this doc page](https://palmr.kyantech.com.br/docs/3.0-beta/s3-providers)

```
services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=true
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
      - S3_ENDPOINT=s3.<redacted>.org
      - S3_PORT=443
      - S3_USE_SSL=true
      - S3_ACCESS_KEY=<redacted>
      - S3_SECRET_KEY=<redacted>
      - S3_REGION="us"
      - S3_BUCKET_NAME="fileshare"
      - S3_FORCE_PATH_STYLE=true
    ports:
      - "5487:5487" # Web port
      - "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY, IF YOU DONT WANT TO EXPOSE THE API, JUST REMOVE$
    volumes:
      - ./palmr:/app/server  # Volume for the application data
    restart: unless-stopped # Restart the container unless it is stopped
volumes:
  palmr_data:
```

However it doesn't seem to be trying to connect to S3, with this in my ``server.out.log``

```
📦 Storage mode: Local Filesystem (Encrypted)
```

Full Log:
```
/var/log/supervisor # cat server.out.log
Starting Palmr Server with SQLite...
Generating Prisma client...
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v6.4.1) to ./node_modules/.pnpm/@prisma+client@6.4.1_prisma@6.4.1_typescript@5.7.3__typescript@5.7.3/node_modules/@prisma/client in 148ms

Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)

Tip: Want to turn off tips and other hints? https://pris.ly/tip-4-nohints

Pushing database schema...
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "palmr.db" at "file:./palmr.db"

SQLite database palmr.db created at file:./palmr.db

🚀  Your database is now in sync with your Prisma schema. Done in 170ms

✔ Generated Prisma Client (v6.4.1) to ./node_modules/.pnpm/@prisma+client@6.4.1_
prisma@6.4.1_typescript@5.7.3__typescript@5.7.3/node_modules/@prisma/client in 1
86ms

Running database seeds...
🌱 Starting app configurations seed...
🛡️  Protected mode: Only creates missing configurations
✅ Created configuration: appName
✅ Created configuration: showHomePage
✅ Created configuration: appDescription
✅ Created configuration: appLogo
✅ Created configuration: firstUserAccess
✅ Created configuration: maxFileSize
✅ Created configuration: maxTotalStoragePerUser
✅ Created configuration: jwtSecret
✅ Created configuration: maxLoginAttempts
✅ Created configuration: loginBlockDuration
✅ Created configuration: passwordMinLength
✅ Created configuration: smtpEnabled
✅ Created configuration: smtpHost
✅ Created configuration: smtpPort
✅ Created configuration: smtpUser
✅ Created configuration: smtpPass
✅ Created configuration: smtpFromName
✅ Created configuration: smtpFromEmail
✅ Created configuration: passwordResetTokenExpiration
✅ Created configuration: oidcEnabled
✅ Created configuration: oidcIssuerUrl
✅ Created configuration: oidcClientId
✅ Created configuration: oidcClientSecret
✅ Created configuration: oidcRedirectUri
✅ Created configuration: oidcScope
✅ Created configuration: oidcAutoRegister
✅ Created configuration: oidcAdminEmailDomains
✅ Created configuration: serverUrl

📊 Seed Summary:
   ✅ Created: 28 configurations
   ⏭️  Skipped: 0 configurations
🎉 App configurations seeded successfully!
Starting server application...
{"level":30,"time":1749965240484,"pid":10,"hostname":"4984224b6a61","msg":"Server listening at http://127.0.0.1:3333"}
{"level":30,"time":1749965240484,"pid":10,"hostname":"4984224b6a61","msg":"Server listening at http://192.168.97.2:3333"}
🌴 Palmr server running on port 3333 🌴
📦 Storage mode: Local Filesystem (Encrypted)
🔐 OIDC SSO: Disabled

📚 API Documentation:
   - API Reference: http://localhost:3333/docs
 ```
