### ISSUE TITLE
services.palmr Additional property network is not allowed

### ISSUE THREAD

**Issue by stormyark** [kyantech/Palmr#53]
I’d like to self-host palmr and expose it via Nginx using the Nginx Proxy Manager.
To do that securely, I usually define an internal network in my `docker-compose.yml` and connect both containers (Nginx and the app) to that network.

However, when trying this with palmr, I get the following error when validating the compose file:

validating /opt/docker-compose/palmr/docker-compose.yml: services.palmr Additional property network is not allowed

It seems the project restricts custom network definitions, which makes it harder to integrate with common self-hosting setups.

Would it be possible to allow defining custom networks in the docker-compose.yml so palmr can be used behind reverse proxies like Nginx?

Thanks in advance!

Here is my `docker-compose.yml:`

```
services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
    ports:
      - "5487:5487" # Web port
      - "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY)
    volumes:
      - ./palmr_data:/app/server # Volume for the application data
    restart: unless-stopped # Restart the container unless it is stopped
    network:
      - network

network:
  network:
    external: true
```

**Comment by clbx** [comment]
This is not a palmr issue, but a typo in your docker compose. 

The correct property is ``networks`` not ``network``

Try: 

```
networks:
  network:
    external: true
```

**Comment by danielalves96** [comment]
> **Note**  
> If you're trying to reverse proxy Palmr behind **Nginx Proxy Manager** using a custom Docker network, that's totally supported — but there's a common mistake that causes the following validation error:

```bash
validating /opt/docker-compose/palmr/docker-compose.yml: services.palmr Additional property network is not allowed
```

> **Warning**  
> The error is caused by using `network` (singular) inside your service block. Docker Compose expects `networks` (plural) when connecting a service to one or more networks.

### Incorrect:
```yaml
services:
  palmr:
    ...
    network:
      - network
```

### Correct:
```yaml
services:
  palmr:
    ...
    networks:
      - network

networks:
  network:
    external: true
```

> **Note**  
> Using `networks` properly ensures your app container and reverse proxy can communicate securely over an internal bridge, avoiding public exposure of sensitive ports.
