### ISSUE TITLE
Error while creating the administrator user

### ISSUE THREAD

**Issue by Jonuji** [kyantech/Palmr#63]
I tried to install Palmr with Docker Compose and secured it via traefik.
Everything until this steps works, but if I try to "login" and register the admin user, it won't work and a error message shows up.

Did I do something wrong, or is anything not working right? I also tried to destroying the container, but still not working.

Here the (important) snippet of the **docker log**:
```
palmr  | {"level":30,"time":1750247915687,"pid":9,"hostname":"7937a4278979","reqId":"req-12","req":{"method":"GET","url":"/auth/me","host":"127.0.0.1:3333","remoteAddress":"127.0.0.1","remotePort":47636},"msg":"incoming request"}
palmr  | FastifyError [Error]: No Authorization was found in request.cookies
palmr  |     at lookupToken (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.0.4/node_modules/@fastify/jwt/jwt.js:272:17)
palmr  |     at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.0.4/node_modules/@fastify/jwt/jwt.js:487:15)
palmr  |     at useGlobalOptions (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.0.4/node_modules/@fastify/jwt/jwt.js:455:31)
palmr  |     at new Promise ()
palmr  |     at _Request.requestVerify [as jwtVerify] (/app/palmr-app/node_modules/.pnpm/@fastify+jwt@9.0.4/node_modules/@fastify/jwt/jwt.js:454:14)
palmr  |     at Object.preValidation (/app/palmr-app/dist/modules/auth/routes.js:114:31)
palmr  |     at hookIterator (/app/palmr-app/node_modules/.pnpm/fastify@5.2.1/node_modules/fastify/lib/hooks.js:408:10)
palmr  |     at next (/app/palmr-app/node_modules/.pnpm/fastify@5.2.1/node_modules/fastify/lib/hooks.js:242:18)
palmr  |     at hookRunner (/app/palmr-app/node_modules/.pnpm/fastify@5.2.1/node_modules/fastify/lib/hooks.js:264:5)
palmr  |     at handler (/app/palmr-app/node_modules/.pnpm/fastify@5.2.1/node_modules/fastify/lib/handleRequest.js:66:7) {
palmr  |   code: 'FST_JWT_NO_AUTHORIZATION_IN_COOKIE',
palmr  |   statusCode: 401
palmr  | }
palmr  | {"level":30,"time":1750247915690,"pid":9,"hostname":"7937a4278979","reqId":"req-12","res":{"statusCode":401},"responseTime":2.1809010058641434,"msg":"request completed"}
```

My **docker compose**:
```
services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY= # CHANGE THIS KEY FOR SECURITY <------- Don't worry, I changed this!
    ports:
      - "5487:5487" # Web interface
#      - "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY) <------- Also tried to activate this
    volumes:
      - palmr_data:/app/server # Named volume for the application data
    restart: unless-stopped # Restart the container unless it is stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.palmr.rule=Host(`palmr.[domain].[tld]`)" <------- Don't worry, I changed this!
      - "traefik.http.routers.palmr.entrypoints=websecure"
      - "traefik.http.routers.palmr.tls=true"
      - "traefik.http.routers.palmr.tls.certresolver=letsencrypt"
      - "traefik.http.services.palmr.loadbalancer.server.port=5487"
      - "traefik.docker.network=traefik-network"

 
volumes:
  palmr_data:

networks:
  traefik-network:
    external: true
```
